name: Feature Request
description: Suggest an idea
labels: ["new-feature"]
assignees:
  - steveh259
body:
  - type: markdown
    attributes:
      value: Thank you for suggesting an idea!
  - type: textarea
    attributes:
      label: Suggestion
      description: Please explain what feature you'd like to see. Don't leave anything out!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: If you'd like to add anything else, do so here!
    validations:
      required: false